services:
  hello:
    build:
      context: ./source
      dockerfile: Dockerfile
    container_name: hello-service
    environment:
      - PYTHONUNBUFFERED=1
    # Для интерактивного CLI нужен stdin_open и tty
    stdin_open: true
    tty: true
    # только агрументы командной строки, добавляются к ENTRYPOINT
    command: ["Docker", "--formal", "--lastname", "User"]
